### ISSUE TITLE
Melhorias no arquivo build.sh

### ISSUE THREAD

**Issue by felipefernandes** [CodeClubBrasil/cci-community-wordpress-theme#1]
**No arquivo build o nome dos containers dão bug no instanciamento**
O que aconteceu quando instanciei a imagem lá no servidor é que o nome do container ficou diferente, daí o build não o reconheceu e não fez, nem a instalação do WP, nem a instalação do plugin. Vale para o nome do container de DB e o WP.

**Comment by maurucao** [comment]
Já vou ajustar usando no YML container_name: cc-wp assim fixamos o nome em vez de usar o do path corrente.

**Comment by maurucao** [comment]
resolvido no develop
